/*
	oooooooooo.                 .
	`888'   `Y8b              .o8
	 888      888  .oooo.   .o888oo  .oooo.
	 888      888 `P  )88b    888   `P  )88b
	 888      888  .oP"888    888    .oP"888
	 888     d88' d8(  888    888 . d8(  888
	o888bood8P'   `Y888""8o   "888" `Y888""8o
*/

#define MAX_ACCOUNT_CHARACTER 3
#define MAX_RADIO_SLOTS 5

// Spawn Points
enum
{
	SPAWN_POINT_DEFAULT,
	SPAWN_POINT_LAST_POS,
	SPAWN_POINT_FACTION,
	MAX_SPAWN_POINT
}

new g_arrSpawnNames[MAX_SPAWN_POINT][32] = {
	"Unity Station (padrão)",
	"Última posição",
	"Spawn da facção"
};

// Account
enum E_ACCOUNT_DATA
{
	e_ACCOUNT_ID,
	e_ACCOUNT_NAME[MAX_PLAYER_NAME + 1],
	e_ACCOUNT_ADMIN,
	bool:e_ACCOUNT_ADMIN_HIDE,
	bool:e_ACCOUNT_ADMIN_VIEW_CHATS,
	e_ACCOUNT_ADMIN_AVALIATIONS,
	e_ACCOUNT_ADMIN_STARS,
	e_ACCOUNT_ADMIN_TEAMS,
	e_ACCOUNT_PREMIUM,
	e_ACCOUNT_PREMIUM_EXPIRES,

	// Temporary
	bool:e_ACCOUNT_ADMIN_DUTY,
	bool:e_ACCOUNT_ADMIN_TEMP
}

new AccountData[MAX_PLAYERS + 1][E_ACCOUNT_DATA];

// Character
enum E_CHARACTER_DATA
{
	e_CHARACTER_ID,
	e_CHARACTER_NAME[MAX_PLAYER_NAME + 1],
	e_CHARACTER_MONEY,
	e_CHARACTER_BANK_MONEY,
	e_CHARACTER_LEVEL,
	e_CHARACTER_EXP,
	e_CHARACTER_THIRST,
	e_CHARACTER_HUNGER,
	e_CHARACTER_SKIN,
	e_CHARACTER_SPAWN_POINT,
	e_CHARACTER_SPAWN_ID,
	e_CHARACTER_SPAWN_EXPIRES,
	Float:e_CHARACTER_HEALTH,
	Float:e_CHARACTER_ARMOUR,
	e_CHARACTER_JOB,
	e_CHARACTER_JOB_HOURS[MAX_JOB],
	e_CHARACTER_PAYCHECK,
	e_CHARACTER_FACTION,
	e_CHARACTER_FACTION_MOD,
	e_CHARACTER_FACTION_RANK[32],

	bool:e_CHARACTER_RADIO_ON,
	e_CHARACTER_RADIO_CHANNELS[MAX_RADIO_SLOTS],

	e_CHARACTER_HEIGHT,
	e_CHARACTER_WEIGHT,
	e_CHARACTER_EYES[16 + 1],
	e_CHARACTER_ETNIA[22 + 1],
	e_CHARACTER_ORIGIN[32 + 1],
	e_CHARACTER_BIRTHDATE[10 + 1],

	// Temporary
	e_CHARACTER_LOADED_TIME,
	bool:e_CHARACTER_FACTION_DUTY,
	Float:e_CHARACTER_POS[3],
	Float:e_CHARACTER_ANGLE,
	e_CHARACTER_INTERIOR,
	e_CHARACTER_WORLD
}

new CharacterData[MAX_PLAYERS + 1][E_CHARACTER_DATA];

enum E_LOOKUP_DATA
{
	bool:e_LOOKUP_SUCCESS,
	bool:e_LOOKUP_VPN,
	e_LOOKUP_CONTINENT[64],
	e_LOOKUP_COUNTRY[64],
	e_LOOKUP_STATE[64],
	e_LOOKUP_CITY[64],
	e_LOOKUP_ISP[64],
	e_LOOKUP_ORG[64],
	e_LOOKUP_AS[64]
}

new LookupData[MAX_PLAYERS][E_LOOKUP_DATA];